project_id = "oilnybhaboefqyhjrmvl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325

[storage]
enabled = true
port = 54326

[functions.serve-content]
verify_jwt = false