
project_id = "oilnybhaboefqyhjrmvl"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "https://fitclub.app.br"
additional_redirect_urls = ["https://fitclub.app.br", "https://oilnybhaboefqyhjrmvl.lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[functions]
verify_jwt = false

[functions.process-delay-tasks]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.generate-secure-download-link]
verify_jwt = false

[functions.generate-patient-link]
verify_jwt = false

[functions.send-form-notification]
verify_jwt = false

[functions.serve-content]
verify_jwt = false

[functions.cron-delay-processor]
verify_jwt = false

[functions.test-flow-simulation]
verify_jwt = false

[functions.test-delay-tasks]
verify_jwt = false

[functions.send-patient-invitation]
verify_jwt = false
